stages:
  - build
  - deploy

variables:
  env: dev

install_dependencies:
  image: node:14.15.0-stretch
  stage: build
  script:
    - export REACT_APP_API_URL=/api/v1/
    - npm install
    - npm run build
    - mv build build_$env
  artifacts:
    paths:
      - node_modules
      - build_$env
  cache:
    paths:
      - node_modules
  only:
    - develop

deploy:
  stage: deploy
  script:
    - apk update
    - apk add --no-cache openssh-client bash
    - mkdir -p /www/dev/
    - cp -r build_$env /www/dev/
    - scp -i $DEPLOY_DEV_FILE -o StrictHostKeyChecking=no -r /www/dev/build_$env/* student@dev.brain4you.ru:/srv/build/build_dev/
  only:
    - develop
    - merge_requests