stages:
  - build
  - deploy

variables:
  docker_html_path: "/www"
  env: dev

install_dependencies:
  image: node:14.15.0-stretch
  stage: build
  script:
    - export REACT_APP_API_URL=http://dev.brain4you.ru/api/v1
    - yarn install
    - yarn build
    - mv build build_$env
  artifacts:
    paths:
      - node_modules
      - build_$env
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
  only:
    - develop

deploy_dev:
  stage: deploy
  script:
    - rm -rf $docker_html_path/build_$env
    - cp -r build_$env $docker_html_path
  only:
    - develop


