stages:
  - build
  - deploy

variables:
  env: dev

install_dependencies:
  image: node:14.15.0-stretch
  stage: build
  script:
    - export REACT_APP_API_URL=/api/v1/
    - npm install
    - npm run build
    - mv build build_$env
  artifacts:
    paths:
      - node_modules
      - build_$env
  cache:
    paths:
      - node_modules
  only:
    - develop

deploy:
  stage: deploy
  before_script:
    - apk update
    - apk add --no-cache openssh-client bash
    - mkdir -p /www/
    - cp -r build_$env /www/
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_DEV_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan dev.brain4you.ru >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:  
    - bash deploy.sh
  only:
    - develop
    - merge_requests