export { PageWrapper } from './PageWrapper'
export { SpinLoader } from './SpinLoader'
export * from './NavMenu'
export * from './UserMenu'
export { FormInputPhone } from './FormInputPhone'
export { FormInputPass } from './FormInputPass'
export { RightAgreementBox } from './RightsAgreementBox'
export { PageContent } from './PageContent'
export { TabTickets } from './TabTickets'
export { TabTicketsHistory } from './TabTicketsHistory'
export { UploadFile } from './UploadFile'
export { SelectTicketsStatus } from './SelectTicketsStatus'
